@startumltitle Quizzifyclass RouterLoader <script>class quizRoutes <JSON>class QuizLoader <script>class quizData <JSON>class Quiz {    quizData    quizObject    renderQuiz()    correctQuiz()    saveResults()}class QuizSingleChoice {    quizData    renderQuiz()    correctQuiz()}class index <html>class style <css>'-------------------------------------------- Quiz o-down- QuizSingleChoice RouterLoader -down-> quizRoutes QuizLoader -down-> quizData Quiz --> quizData @enduml